double swish(double x);
double dswish(double x);
double relu(double x);
double drelu(double x);
double lerelu(double x);
double dlerelu(double x);
double hyptan(double x);
double dhyptan(double x);
double sigmoid(double x);
double dsigmoid(double x);
double softsign(double x);
double dsoftsign(double x);
double elu(double x);
double delu(double x);
void softmax(int distance, int count, double *values);